import Head from "next/head";
import MapComponent from "../components/MapComponent";
import { useRef, useCallback, useState } from "react";
import Dashboard from "../components/Dashboard";
import { useSession } from "next-auth/react";
import { useQuery } from "react-query";



export default function Home() {
  const { data: session } = useSession()

  const { isLoading, error, data } = useQuery(['repoData'], () =>
    fetch('/api/users').then(res =>
      res.json()))
  console.log(isLoading, error, data)


  return (
    <div>
      <Head>
        <title>Cafe Comprende</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://cdn.shopify.com/s/files/1/0299/2046/0884/files/SyraCoffee_-_CoffeeThunderboltLogoBlac-Espacio_600x_1_1024x1024.png?v=1624869379"
        />
      </Head>
      <main className="flex">
        <MapComponent />
        <div className="h-[100vh] w-[30vw] overflow-scroll">
          <Dashboard />
        </div>
      </main>
    </div>
  );
}
