import Head from "next/head";
import { Dashboard, MapComponent, MobileList } from "../components";
import useWindowSize from "../hooks/useWindowSize";
import { MOBILE_BREAKPOINT } from "../utils/constants";
import { useSession } from "next-auth/react";
import { Toaster } from "react-hot-toast";
import { prisma } from "../utils/prisma";
import { dehydrate, QueryClient } from "@tanstack/react-query";

export async function getStaticProps() {
  const queryClient = new QueryClient();
  await queryClient.fetchQuery(
    ["cafes"],
    async () =>
      await prisma.cafe.findMany({
        orderBy: {
          updatedAt: "desc",
        },
        select: {
          reviews: true,
          latitude: true,
          longitude: true,
          place_id: true,
          name: true,
        },
      })
  );
  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
}

export default function Home() {
  const { data: session } = useSession();
  const { height, width } = useWindowSize();

  return (
    <main
      style={{ height: `${height}px` }}
      className={`flex flex-col antialiased md:flex-row`}
    >
      <Head>
        {process.env.NODE_ENV == "production" ? (
          <title>Cafe Comprende</title>
        ) : (
          <title>LOCALHOST CAFE</title>
        )}
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://cdn.shopify.com/s/files/1/0299/2046/0884/files/SyraCoffee_-_CoffeeThunderboltLogoBlac-Espacio_600x_1_1024x1024.png?v=1624869379"
        />
      </Head>
      <Dashboard />
      <MapComponent />
      {width < MOBILE_BREAKPOINT && <MobileList />}
      <Toaster position="bottom-center" reverseOrder={false} />
    </main>
  );
}
