import Head from "next/head";
import MapComponent from "../components/MapComponent";
import { useRef, useCallback, useState } from "react";
import Dashboard from "../components/Dashboard";
import { useMutation, useQuery } from "react-query";
import PlaceList from "../components/PlaceList";
import FeaturedCafe from "../components/FeaturedCafe";
import { ChevronUpIcon } from "@heroicons/react/solid";


export default function Home() {

  console.log(process.env.NODE_ENV);

  return (
    <div>
      <Head>
        <title>Cafe Comprende</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://cdn.shopify.com/s/files/1/0299/2046/0884/files/SyraCoffee_-_CoffeeThunderboltLogoBlac-Espacio_600x_1_1024x1024.png?v=1624869379"
        />
      </Head>
      <main className="relative flex flex-col h-[100vh] md:flex-row">
        <div className="md:w-2/6 md:h-full md:overflow-y-auto">
          <Dashboard />
          {/* <PlaceList /> */}
        </div>
        <MapComponent />
      </main>
    </div>
  );
}
