import Head from "next/head";
import { Dashboard, MapComponent, MobileList } from "../components";
import { useProfile } from "../hooks/useProfile";
import useWindowSize from "../hooks/useWindowSize";
import { MOBILE_BREAKPOINT } from "../utils/constants";
import { useSession } from "next-auth/react";
import { Toaster } from "react-hot-toast";

export default function Home() {
  const { data: session } = useSession();
  const { height, width } = useWindowSize();

  const { isLoading, isError, error, data } = useProfile({
    email: (session?.user?.email && session?.user?.email) as string,
    enabled: !!session?.user?.email,
  });

  return (
    <main
      style={{ height: `${height}px` }}
      className={`flex flex-col antialiased md:flex-row`}
    >
      <Head>
        {process.env.NODE_ENV == "production" ? (
          <title>Cafe Comprende</title>
        ) : (
          <title>LOCALHOST CAFE</title>
        )}
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://cdn.shopify.com/s/files/1/0299/2046/0884/files/SyraCoffee_-_CoffeeThunderboltLogoBlac-Espacio_600x_1_1024x1024.png?v=1624869379"
        />
      </Head>
      <Dashboard />
      <MapComponent />
      {width < MOBILE_BREAKPOINT && <MobileList />}
      <Toaster position="bottom-center" reverseOrder={false} />
    </main>
  );
}
